# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# extract_point.py
# Created on: 2017-05-25 08:58:23.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy
import os
import fnmatch

arcpy.env.overwriteOutput = True

excelfilefolder="C:\\GF\\GF_STAT_CSV\\"
outputfolder="C:\\GF\\GF_STAT_DBF\\"

pattern = '*.csv'
excelfiles=fnmatch.filter(os.listdir(excelfilefolder), pattern)
arcpy.CheckOutExtension("spatial")
i=0
for excelfile in excelfiles:
    i=i+1
    intable=os.path.join(excelfilefolder,excelfile)
    outDBFname=os.path.join(outputfolder,excelfile[:-4]+".dbf")
    Table_Layer = "firestations_layer"+str(i)
    fields= arcpy.ListFields(intable)
    # Create a fieldinfo object
    fieldinfo = arcpy.FieldInfo()
    # The created crime_view layer will have fields as set in fieldinfo object
    arcpy.MakeTableView_management(intable, Table_Layer, "", "", fieldinfo)
    arcpy.CopyRows_management(Table_Layer, outDBFname)
    arcpy.AddField_management(outDBFname, "IDD", "TEXT", "", "", "10", "", "NULLABLE", "NON_REQUIRED", "")
    arcpy.CalculateField_management(outDBFname, "IDD", "\""+excelfile[:-4]+"\"", "VB", "")
    print outDBFname+" is ok!"
